### ISSUE TITLE
Pydantic Import Error

### ISSUE THREAD

**Issue by PabloB94** [imagegenius/docker-immich-cuda-node#13]
I installed the container using the following command:

    docker run -d
    --name='Immich-CUDA-Node'
    --net='ceres'  
    -e 'TZ'='Europe/ES'  
    -e 'PUID'='1000'  
    -e 'PGID'='1000'  
    -p '3003:3003/tcp'   
    -v '/mnt/user/appdata/immich-cuda-node':'/config':'rw'   
    --gpus=all 'ghcr.io/imagegenius/immich-cuda-node:latest'  

Whenever I try to start the container, I get the following error:
 
    Traceback (most recent call last):\
      File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main\
        return _run_code(code, main_globals, None,\
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code\
        exec(code, run_globals)\
      File "/app/immich/machine-learning/app/main.py", line 11, in <module>\
        from .config import settings\
      File "/app/immich/machine-learning/app/config.py", line 3, in <module>\
        from pydantic import BaseSettings\
      File "/config/cuda-venv/lib/python3.10/site-packages/pydantic/__init__.py", line 207, in __getattr__\
        return _getattr_migration(attr_name)\
      File "/config/cuda-venv/lib/python3.10/site-packages/pydantic/_migration.py", line 288, in wrapper\
        raise PydanticImportError(\
    pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.

I don't really know if this is an immich-cuda-node problem or if it's some dependency that needs to be updated upstream. I'm not sure how to proceed.   
I'm using Unraid  6.12.2, Docker version 20.10.34.  
Any help would be appreciated. Thanks!

**Comment by flex420** [comment]
same here - guess there is no fix?
